#%RAML 1.0 DataType

type: object
properties: 
  associateAssignments:
    type: object
    active: boolean
      associate:
        email: string
        firstName: string
        flag:
            content: string
            id: integer
            type: string
        lastName: string
        salesforceid: string
        trainingAssignments: array