#%RAML 1.0 DataType

type: object
properties: 
  AssociateId?: string
  BatchId: string
  Content: string
  CreatedOn: string
  EmployeeId: string
  LastUpdated: string
  NoteId: integer
  TechnicalStatus: string
  Type: string
  Week: integer