#%RAML 1.0 NamedExample

value:
  -
    assessmentId: 63
    rawScore: 100
    assessmentTitle: Mock Assessment 1-0
    assessmentType: Presentation
    weekNumber: 1
    batchId: TR-1028
    assessmentCategory: 5
    assignmentDate: 01-01-2020
  -
    assessmentId: 64
    rawScore: 100
    assessmentTitle: Mock Assessment 1-1
    assessmentType: Presentation
    weekNumber: 1
    batchId: TR-1028
    assessmentCategory: 39
    assignmentDate: 02-02-2020