#%RAML 1.0 NamedExample

value:
  - 
    id: 16
    batchId: TR-1028
    name: Mock Batch 16
    startDate: 2020-04-01
    endDate: 2020-06-10
    skill: Java React
    location: Reston
    type: Corporate
    goodGrade: 70
    passingGrade: 80
    employeeAssignments:
        role: ROLE_LEAD_TRAINER
        employee:
          email: mock1022.employee870e1a69-f385-4cdb-9c59-986de917eca4@mock.com
          firstName: Mock 1022
          lastName: Employee 1022
        deletedAt: null
  - 
    associateAssignments:
      -
        trainingStatus: Training
        associate:
          email: mock0.associate59e1088a-6e5d-4cb7-9d36-9463a2beb2bc@mock.com
          salesforceId: SF-1250
          firstName: Mock 0
          lastName: Associate 0
          flag: null
        startDate: 2020-06-10
        endDate: 2020-04-01
        active: true
      -
        trainingStatus: Training
        associate:
          email: mock10.associate6d293e73-1aec-48a5-a0ed-ed8829c9e7f3@mock.com
          salesforceId: SF-1260
          firstName: Mock 10
          lastName: Associate 10
          flag: null
        startDate: 2020-06-10
        endDate: 2020-04-01
        active: true
    currentWeek: 11